---
- hosts: 127.0.0.1
  any_errors_fatal: yes
  gather_facts: no

  roles:
    - { role: common, tags: ["always"] }
    - { role: apps,   tags: ["always"] }
    - { role: p20n,   tags: ["always"] }
    - { role: swdev,  tags: ["always"] }
    - { role: emus,   tags: ["never", "emus"] }
