---
- name: python3 venv
  become: yes
  apt:
    name:
      - python3.12-venv

- name: include docker
  include_tasks: docker.yml

- name: include nvm
  include_tasks: nvm.yml

- name: include vscode
  include_tasks: vscode.yml
