---
- name: common tooling
  become: yes
  apt:
    name:
    - ack-grep
    - bat
    - curl
    - emacs
    - eza
    - ffmpeg
    - pass
    - tig
    - tree
    state: present

- name: vim is a synonym for vi
  become: yes
  file:
    state: link
    src: /usr/bin/vi
    dest: /usr/local/bin/vim

- name: remove useless packages (apt) from the cache
  become: yes
  apt:
    autoclean: yes

- name: remove dependencies (apt) that are no longer required
  become: yes
  apt:
    autoremove: yes
